# -*- coding: utf-8 -*-
# Example of generated architecture.py file
# This file is automatically generated by generate_architecture.py
# DO NOT edit manually - changes will be lost on next generation

from diagrams import Diagram, Cluster, Edge
from diagrams.aws.compute import ECS
from diagrams.aws.database import RDS
from diagrams.aws.storage import S3
from diagrams.onprem.database import Mongodb
from diagrams.onprem.client import Users

graph_attr = {
    "fontsize": "18",
    "bgcolor": "white",
    "splines": "ortho",
    "nodesep": "1.5",
    "ranksep": "2.5",
    "pad": "1.0"
}

with Diagram(
    "FastAPI Application Architecture",
    show=False,
    filename="architecture_diagram",
    outformat="png",
    direction="TB",
    graph_attr=graph_attr
):

    users = Users("API Clients\nUsers")

    with Cluster("Application Layer"):
        app_server = ECS("FastAPI Application\n(Uvicorn Server)")
        
        with Cluster("API Endpoints"):
            rest_api = ECS("REST API\n15 Controllers")
            graphql_api = ECS("GraphQL API\nStrawberry")
        
        with Cluster("Business Logic"):
            services = ECS("Services Layer\n20 Services")
            models = ECS("Data Models\nSQLAlchemy")
        
        background_jobs = ECS("Background Jobs\nAPScheduler")

    with Cluster("Data Layer"):
        postgres = RDS("PostgreSQL\nMain Database")
        mongodb = Mongodb("MongoDB\nDocument Database")

    with Cluster("Storage"):
        s3_storage = S3("S3 Storage\nFiles & Documents")

    # ------------------
    # FLOWS
    # ------------------

    # Client to application
    users >> app_server

    # Application to API endpoints
    app_server >> rest_api
    app_server >> graphql_api
    rest_api >> services
    graphql_api >> services

    # Business logic flow
    services >> models

    # Database connections
    models >> Edge(label="Read/Write") >> postgres
    services >> Edge(label="Document Store") >> mongodb

    # File storage flow
    services >> Edge(label="Store/Retrieve Files") >> s3_storage

    # AI Detected 25 service-to-service relationships
    # (Services shown as group; individual connections not displayed)

    # Background job flows
    background_jobs >> Edge(style="dashed", label="Scheduled Tasks") >> services
    background_jobs >> Edge(style="dashed") >> postgres
    background_jobs >> Edge(style="dashed") >> mongodb