#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Automatic Architecture Generator for Auto Architecture Diagrams
Generates architecture.py based on repository analysis with AI refinement
"""
import json
from pathlib import Path
from typing import Dict

try:
    import sys
    from pathlib import Path
    # Add current directory to path for ai_refiner import
    current_dir = Path(__file__).parent
    if str(current_dir) not in sys.path:
        sys.path.insert(0, str(current_dir))
    from ai_refiner import AIRefiner
    AI_AVAILABLE = True
except ImportError as e:
    AI_AVAILABLE = False
    print(f"⚠️ AI module not available: {e}")
    print("   Generating without refinement...")
except Exception as e:
    AI_AVAILABLE = False
    print(f"⚠️ Error loading AI module: {e}")
    print("   Generating without refinement...")

class ArchitectureGenerator:
    def __init__(self, analysis_file: str = None):
        if analysis_file is None:
            analysis_file = Path(__file__).parent / "analysis_result.json"
        else:
            analysis_file = Path(analysis_file)
        
        with open(analysis_file, "r", encoding="utf-8") as f:
            self.analysis = json.load(f)
        
        self.components = self.analysis["components"]
        self.summary = self.analysis["summary"]
    
    def generate(self, use_ai_refinement: bool = True) -> str:
        """Generates Python code for architecture.py"""
        code = self._generate_header()
        code += self._generate_imports()
        code += self._generate_diagram_config()
        code += self._generate_diagram_structure()
        code += self._generate_flows()
        
        # Apply AI refinement if available
        if use_ai_refinement and AI_AVAILABLE:
            try:
                print("🤖 Starting AI refinement...")
                refiner = AIRefiner()
                print("   Analyzing relationships...")
                refiner.analyze_relationships()
                print("   Generating suggestions...")
                refiner.generate_suggestions()
                print("   Applying refinements...")
                code = refiner.refine_architecture_code(code)
                refiner.save_refinement_report()
                print("✨ AI refinement applied successfully")
            except FileNotFoundError as e:
                print(f"⚠️ File not found: {e}")
                print("   Make sure to run analyze_repo.py first")
                print("   Continuing without refinement...")
            except Exception as e:
                import traceback
                print(f"⚠️ AI refinement error: {e}")
                print(f"   Details: {traceback.format_exc()}")
                print("   Continuing without refinement...")
        
        return code
    
    def _generate_header(self) -> str:
        return '''# -*- coding: utf-8 -*-
# This file is automatically generated by generate_architecture.py
# DO NOT edit manually - changes will be lost on next generation
# To modify the diagram, edit analyze_repo.py or generate_architecture.py

'''
    
    def _generate_imports(self) -> str:
        imports = ["from diagrams import Diagram, Cluster, Edge"]
        
        # AWS imports
        if self.summary.get("aws_services"):
            imports.append("from diagrams.aws.compute import ECS")
            
            if "RDS" in self.summary["aws_services"] or "PostgreSQL" in self.summary["databases"]:
                imports.append("from diagrams.aws.database import RDS")
            
            if "S3" in self.summary["aws_services"]:
                imports.append("from diagrams.aws.storage import S3")
            
            if "DynamoDB" in self.summary["aws_services"]:
                imports.append("from diagrams.aws.database import Dynamodb")
            
            if "Lambda" in self.summary["aws_services"]:
                imports.append("from diagrams.aws.compute import Lambda")
            
            if "SNS" in self.summary["aws_services"]:
                imports.append("from diagrams.aws.integration import SNS")
            
            if "SQS" in self.summary["aws_services"]:
                imports.append("from diagrams.aws.integration import SQS")
        
        # GCP imports
        if self.summary.get("gcp_services"):
            if "Cloud Storage" in self.summary["gcp_services"]:
                imports.append("from diagrams.gcp.storage import GCS")
            if "BigQuery" in self.summary["gcp_services"]:
                imports.append("from diagrams.gcp.analytics import BigQuery")
        
        # On-premise databases
        if "MongoDB" in self.summary["databases"]:
            imports.append("from diagrams.onprem.database import Mongodb")
        
        if "MySQL" in self.summary["databases"]:
            imports.append("from diagrams.onprem.database import Mysql")
        
        if "Redis" in self.summary["databases"]:
            imports.append("from diagrams.onprem.inmemory import Redis")
        
        # Generic components
        imports.append("from diagrams.onprem.client import Users")
        
        # Add compute if no cloud services detected
        if not self.summary.get("aws_services") and not self.summary.get("gcp_services"):
            imports.append("from diagrams.onprem.compute import Server")
        
        return "\n".join(imports) + "\n\n"
    
    def _generate_diagram_config(self) -> str:
        return '''graph_attr = {
    "fontsize": "18",
    "bgcolor": "white",
    "splines": "ortho",
    "nodesep": "1.5",
    "ranksep": "2.5",
    "pad": "1.0"
}

'''
    
    def _generate_diagram_structure(self) -> str:
        framework = self.summary.get("framework", "Application")
        server = self.summary.get("server", "Server")
        graphql = self.summary.get("graphql")
        
        # Generate diagram title
        title = f"{framework} Architecture" if framework != "Unknown" else "Application Architecture"
        
        code = f'''with Diagram(
    "{title}",
    show=False,
    filename="architecture_diagram",
    outformat="png",
    direction="TB",
    graph_attr=graph_attr
):

    users = Users("API Clients\\nUsers")

    with Cluster("Application Layer"):
'''
        
        # Application server
        if self.summary.get("aws_services"):
            code += f'        app_server = ECS("{framework} Application\\n({server})")\n'
        else:
            code += f'        app_server = Server("{framework} Application\\n({server})")\n'
        
        # API endpoints
        if self.summary['controllers_count'] > 0 or graphql:
            code += '\n        with Cluster("API Endpoints"):\n'
            
            if self.summary['controllers_count'] > 0:
                code += f'            rest_api = ECS("REST API\\n{self.summary["controllers_count"]} Controllers")\n'
            
            if graphql:
                code += f'            graphql_api = ECS("GraphQL API\\n{graphql}")\n'
        
        # Business logic
        if self.summary['services_count'] > 0 or self.summary['models_count'] > 0:
            code += '\n        with Cluster("Business Logic"):\n'
            
            if self.summary['services_count'] > 0:
                code += f'            services = ECS("Services Layer\\n{self.summary["services_count"]} Services")\n'
            
            if self.summary['models_count'] > 0:
                orm = self.summary.get("orm", "ORM")
                code += f'            models = ECS("Data Models\\n{orm}")\n'
        
        # Background jobs
        if self.summary['cron_jobs_count'] > 0:
            scheduler = self.summary.get("scheduler", "Scheduler")
            code += f'\n        background_jobs = ECS("Background Jobs\\n{scheduler}")\n'
        
        # Data layer
        databases = self.summary["databases"]
        if databases:
            code += "\n    with Cluster(\"Data Layer\"):\n"
            
            if "PostgreSQL" in databases:
                if "RDS" in self.summary.get("aws_services", []):
                    code += '        postgres = RDS("PostgreSQL\\nMain Database")\n'
                else:
                    code += '        postgres = Server("PostgreSQL\\nMain Database")\n'
            
            if "MongoDB" in databases:
                code += '        mongodb = Mongodb("MongoDB\\nDocument Database")\n'
            
            if "MySQL" in databases:
                code += '        mysql = Mysql("MySQL\\nRelational Database")\n'
            
            if "Redis" in databases:
                code += '        redis = Redis("Redis\\nCache & Sessions")\n'
            
            if "DynamoDB" in self.summary.get("aws_services", []):
                code += '        dynamodb = Dynamodb("DynamoDB\\nNoSQL Database")\n'
        
        # Storage layer
        storage_services = self.summary.get("aws_services", [])
        if "S3" in storage_services:
            code += '\n    with Cluster("Storage"):\n'
            code += '        s3_storage = S3("S3 Storage\\nFiles & Documents")\n'
        
        # Message queues
        queue_services = [s for s in storage_services if s in ["SNS", "SQS"]]
        if queue_services:
            code += '\n    with Cluster("Message Queues"):\n'
            if "SNS" in queue_services:
                code += '        sns = SNS("SNS\\nNotifications")\n'
            if "SQS" in queue_services:
                code += '        sqs = SQS("SQS\\nMessage Queue")\n'
        
        return code
    
    def _generate_flows(self) -> str:
        code = "\n    # ------------------\n"
        code += "    # FLOWS\n"
        code += "    # ------------------\n\n"
        
        code += "    # Client to application\n"
        code += "    users >> app_server\n\n"
        
        # API flows
        if self.summary['controllers_count'] > 0:
            code += "    # Application to API endpoints\n"
            code += "    app_server >> rest_api\n"
            
            if self.summary.get("graphql"):
                code += "    app_server >> graphql_api\n"
            
            code += "    rest_api >> services\n"
            if self.summary.get("graphql"):
                code += "    graphql_api >> services\n"
            code += "\n"
        
        # Business logic flows
        if self.summary['services_count'] > 0 and self.summary['models_count'] > 0:
            code += "    # Business logic flow\n"
            code += "    services >> models\n\n"
        
        # Database connections
        databases = self.summary["databases"]
        if databases:
            code += "    # Database connections\n"
            
            if "PostgreSQL" in databases:
                if self.summary['models_count'] > 0:
                    code += '    models >> Edge(label="Read/Write") >> postgres\n'
                else:
                    code += '    services >> Edge(label="Read/Write") >> postgres\n'
            
            if "MongoDB" in databases:
                code += '    services >> Edge(label="Document Store") >> mongodb\n'
            
            if "MySQL" in databases:
                code += '    services >> Edge(label="Read/Write") >> mysql\n'
            
            if "Redis" in databases:
                code += '    services >> Edge(label="Cache") >> redis\n'
            
            if "DynamoDB" in self.summary.get("aws_services", []):
                code += '    services >> Edge(label="NoSQL") >> dynamodb\n'
            
            code += "\n"
        
        # Storage flows
        if "S3" in self.summary.get("aws_services", []):
            code += "    # File storage flow\n"
            code += '    services >> Edge(label="Store/Retrieve Files") >> s3_storage\n\n'
        
        # Message queue flows
        queue_services = [s for s in self.summary.get("aws_services", []) if s in ["SNS", "SQS"]]
        if queue_services:
            code += "    # Message queue flows\n"
            if "SNS" in queue_services:
                code += '    services >> Edge(label="Publish") >> sns\n'
            if "SQS" in queue_services:
                code += '    services >> Edge(label="Queue") >> sqs\n'
            code += "\n"
        
        # Background job flows
        if self.summary['cron_jobs_count'] > 0:
            code += "    # Background job flows\n"
            code += '    background_jobs >> Edge(style="dashed", label="Scheduled Tasks") >> services\n'
            
            if "PostgreSQL" in databases:
                code += '    background_jobs >> Edge(style="dashed") >> postgres\n'
            if "MongoDB" in databases:
                code += '    background_jobs >> Edge(style="dashed") >> mongodb\n'
        
        return code


if __name__ == "__main__":
    import sys
    
    use_ai = "--no-ai" not in sys.argv
    
    generator = ArchitectureGenerator()
    architecture_code = generator.generate(use_ai_refinement=use_ai)
    
    # Save to architecture.py
    output_file = Path(__file__).parent / "architecture.py"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(architecture_code)
    
    print(f"✅ architecture.py generated at: {output_file}")
    if use_ai and AI_AVAILABLE:
        print("   (With AI refinement applied)")
    elif not use_ai:
        print("   (AI refinement disabled)")
    else:
        print("   (AI refinement not available)")